// Code generated by protoc-gen-go.
// source: accounts.proto
// DO NOT EDIT!

/*
Package accounts is a generated protocol buffer package.

It is generated from these files:
	accounts.proto

It has these top-level messages:
	NilParam
	AvailabilityResponse
	GenericString
	SignUpRequest
	GenericResponse
	Settings
	NewAccountDetails
	SignInRequest
	Username
*/
package accounts

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NilParam struct {
}

func (m *NilParam) Reset()                    { *m = NilParam{} }
func (m *NilParam) String() string            { return proto.CompactTextString(m) }
func (*NilParam) ProtoMessage()               {}
func (*NilParam) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type AvailabilityResponse struct {
	Available bool `protobuf:"varint,1,opt,name=Available" json:"Available,omitempty"`
}

func (m *AvailabilityResponse) Reset()                    { *m = AvailabilityResponse{} }
func (m *AvailabilityResponse) String() string            { return proto.CompactTextString(m) }
func (*AvailabilityResponse) ProtoMessage()               {}
func (*AvailabilityResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AvailabilityResponse) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

type GenericString struct {
	String_ string `protobuf:"bytes,1,opt,name=String" json:"String,omitempty"`
}

func (m *GenericString) Reset()                    { *m = GenericString{} }
func (m *GenericString) String() string            { return proto.CompactTextString(m) }
func (*GenericString) ProtoMessage()               {}
func (*GenericString) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GenericString) GetString_() string {
	if m != nil {
		return m.String_
	}
	return ""
}

type SignUpRequest struct {
	// At least one field should be present
	EmailAddress string `protobuf:"bytes,1,opt,name=EmailAddress" json:"EmailAddress,omitempty"`
	PhoneNumber  string `protobuf:"bytes,2,opt,name=PhoneNumber" json:"PhoneNumber,omitempty"`
}

func (m *SignUpRequest) Reset()                    { *m = SignUpRequest{} }
func (m *SignUpRequest) String() string            { return proto.CompactTextString(m) }
func (*SignUpRequest) ProtoMessage()               {}
func (*SignUpRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SignUpRequest) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *SignUpRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type GenericResponse struct {
	Status      int32  `protobuf:"varint,1,opt,name=Status" json:"Status,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=Description" json:"Description,omitempty"`
}

func (m *GenericResponse) Reset()                    { *m = GenericResponse{} }
func (m *GenericResponse) String() string            { return proto.CompactTextString(m) }
func (*GenericResponse) ProtoMessage()               {}
func (*GenericResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GenericResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GenericResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Settings struct {
	Settings map[string]string `protobuf:"bytes,1,rep,name=Settings" json:"Settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Settings) Reset()                    { *m = Settings{} }
func (m *Settings) String() string            { return proto.CompactTextString(m) }
func (*Settings) ProtoMessage()               {}
func (*Settings) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Settings) GetSettings() map[string]string {
	if m != nil {
		return m.Settings
	}
	return nil
}

type NewAccountDetails struct {
	// VerificationString can tell which of email or phone is confirmed
	VerificationString string    `protobuf:"bytes,1,opt,name=VerificationString" json:"VerificationString,omitempty"`
	Username           string    `protobuf:"bytes,2,opt,name=Username" json:"Username,omitempty"`
	Password           string    `protobuf:"bytes,3,opt,name=Password" json:"Password,omitempty"`
	Settings           *Settings `protobuf:"bytes,4,opt,name=Settings" json:"Settings,omitempty"`
}

func (m *NewAccountDetails) Reset()                    { *m = NewAccountDetails{} }
func (m *NewAccountDetails) String() string            { return proto.CompactTextString(m) }
func (*NewAccountDetails) ProtoMessage()               {}
func (*NewAccountDetails) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *NewAccountDetails) GetVerificationString() string {
	if m != nil {
		return m.VerificationString
	}
	return ""
}

func (m *NewAccountDetails) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *NewAccountDetails) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *NewAccountDetails) GetSettings() *Settings {
	if m != nil {
		return m.Settings
	}
	return nil
}

type SignInRequest struct {
	Username     string `protobuf:"bytes,1,opt,name=Username" json:"Username,omitempty"`
	EmailAddress string `protobuf:"bytes,2,opt,name=EmailAddress" json:"EmailAddress,omitempty"`
	PhoneNumber  string `protobuf:"bytes,3,opt,name=PhoneNumber" json:"PhoneNumber,omitempty"`
	Password     string `protobuf:"bytes,4,opt,name=Password" json:"Password,omitempty"`
	// Session validity in hours
	Validity int32 `protobuf:"varint,5,opt,name=Validity" json:"Validity,omitempty"`
}

func (m *SignInRequest) Reset()                    { *m = SignInRequest{} }
func (m *SignInRequest) String() string            { return proto.CompactTextString(m) }
func (*SignInRequest) ProtoMessage()               {}
func (*SignInRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *SignInRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SignInRequest) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *SignInRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *SignInRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *SignInRequest) GetValidity() int32 {
	if m != nil {
		return m.Validity
	}
	return 0
}

type Username struct {
	Username string `protobuf:"bytes,1,opt,name=Username" json:"Username,omitempty"`
}

func (m *Username) Reset()                    { *m = Username{} }
func (m *Username) String() string            { return proto.CompactTextString(m) }
func (*Username) ProtoMessage()               {}
func (*Username) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Username) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func init() {
	proto.RegisterType((*NilParam)(nil), "accounts.NilParam")
	proto.RegisterType((*AvailabilityResponse)(nil), "accounts.AvailabilityResponse")
	proto.RegisterType((*GenericString)(nil), "accounts.GenericString")
	proto.RegisterType((*SignUpRequest)(nil), "accounts.SignUpRequest")
	proto.RegisterType((*GenericResponse)(nil), "accounts.GenericResponse")
	proto.RegisterType((*Settings)(nil), "accounts.Settings")
	proto.RegisterType((*NewAccountDetails)(nil), "accounts.NewAccountDetails")
	proto.RegisterType((*SignInRequest)(nil), "accounts.SignInRequest")
	proto.RegisterType((*Username)(nil), "accounts.Username")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Accounts service

type AccountsClient interface {
	SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	CheckAvailability(ctx context.Context, in *Username, opts ...grpc.CallOption) (*AvailabilityResponse, error)
	CreateAccount(ctx context.Context, in *NewAccountDetails, opts ...grpc.CallOption) (*GenericResponse, error)
	SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	UpdateAccount(ctx context.Context, in *Settings, opts ...grpc.CallOption) (*GenericResponse, error)
	UpdateUserName(ctx context.Context, in *Username, opts ...grpc.CallOption) (*GenericResponse, error)
	ChangeEmailAddress(ctx context.Context, in *GenericString, opts ...grpc.CallOption) (*GenericResponse, error)
	ConfirmEmailChange(ctx context.Context, in *GenericString, opts ...grpc.CallOption) (*GenericResponse, error)
	ChangePhone(ctx context.Context, in *GenericString, opts ...grpc.CallOption) (*GenericResponse, error)
	ConfirmPhoneChange(ctx context.Context, in *GenericString, opts ...grpc.CallOption) (*GenericResponse, error)
	SignOut(ctx context.Context, in *NilParam, opts ...grpc.CallOption) (*GenericResponse, error)
	DeleteAccount(ctx context.Context, in *NilParam, opts ...grpc.CallOption) (*GenericResponse, error)
}

type accountsClient struct {
	cc *grpc.ClientConn
}

func NewAccountsClient(cc *grpc.ClientConn) AccountsClient {
	return &accountsClient{cc}
}

func (c *accountsClient) SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := grpc.Invoke(ctx, "/accounts.Accounts/SignUp", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) CheckAvailability(ctx context.Context, in *Username, opts ...grpc.CallOption) (*AvailabilityResponse, error) {
	out := new(AvailabilityResponse)
	err := grpc.Invoke(ctx, "/accounts.Accounts/CheckAvailability", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) CreateAccount(ctx context.Context, in *NewAccountDetails, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := grpc.Invoke(ctx, "/accounts.Accounts/CreateAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := grpc.Invoke(ctx, "/accounts.Accounts/SignIn", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) UpdateAccount(ctx context.Context, in *Settings, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := grpc.Invoke(ctx, "/accounts.Accounts/UpdateAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) UpdateUserName(ctx context.Context, in *Username, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := grpc.Invoke(ctx, "/accounts.Accounts/UpdateUserName", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) ChangeEmailAddress(ctx context.Context, in *GenericString, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := grpc.Invoke(ctx, "/accounts.Accounts/ChangeEmailAddress", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) ConfirmEmailChange(ctx context.Context, in *GenericString, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := grpc.Invoke(ctx, "/accounts.Accounts/ConfirmEmailChange", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) ChangePhone(ctx context.Context, in *GenericString, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := grpc.Invoke(ctx, "/accounts.Accounts/ChangePhone", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) ConfirmPhoneChange(ctx context.Context, in *GenericString, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := grpc.Invoke(ctx, "/accounts.Accounts/ConfirmPhoneChange", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) SignOut(ctx context.Context, in *NilParam, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := grpc.Invoke(ctx, "/accounts.Accounts/SignOut", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) DeleteAccount(ctx context.Context, in *NilParam, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := grpc.Invoke(ctx, "/accounts.Accounts/DeleteAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Accounts service

type AccountsServer interface {
	SignUp(context.Context, *SignUpRequest) (*GenericResponse, error)
	CheckAvailability(context.Context, *Username) (*AvailabilityResponse, error)
	CreateAccount(context.Context, *NewAccountDetails) (*GenericResponse, error)
	SignIn(context.Context, *SignInRequest) (*GenericResponse, error)
	UpdateAccount(context.Context, *Settings) (*GenericResponse, error)
	UpdateUserName(context.Context, *Username) (*GenericResponse, error)
	ChangeEmailAddress(context.Context, *GenericString) (*GenericResponse, error)
	ConfirmEmailChange(context.Context, *GenericString) (*GenericResponse, error)
	ChangePhone(context.Context, *GenericString) (*GenericResponse, error)
	ConfirmPhoneChange(context.Context, *GenericString) (*GenericResponse, error)
	SignOut(context.Context, *NilParam) (*GenericResponse, error)
	DeleteAccount(context.Context, *NilParam) (*GenericResponse, error)
}

func RegisterAccountsServer(s *grpc.Server, srv AccountsServer) {
	s.RegisterService(&_Accounts_serviceDesc, srv)
}

func _Accounts_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.Accounts/SignUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).SignUp(ctx, req.(*SignUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_CheckAvailability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Username)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).CheckAvailability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.Accounts/CheckAvailability",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).CheckAvailability(ctx, req.(*Username))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewAccountDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.Accounts/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).CreateAccount(ctx, req.(*NewAccountDetails))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.Accounts/SignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).SignIn(ctx, req.(*SignInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_UpdateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Settings)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).UpdateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.Accounts/UpdateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).UpdateAccount(ctx, req.(*Settings))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_UpdateUserName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Username)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).UpdateUserName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.Accounts/UpdateUserName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).UpdateUserName(ctx, req.(*Username))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_ChangeEmailAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenericString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).ChangeEmailAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.Accounts/ChangeEmailAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).ChangeEmailAddress(ctx, req.(*GenericString))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_ConfirmEmailChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenericString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).ConfirmEmailChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.Accounts/ConfirmEmailChange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).ConfirmEmailChange(ctx, req.(*GenericString))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_ChangePhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenericString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).ChangePhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.Accounts/ChangePhone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).ChangePhone(ctx, req.(*GenericString))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_ConfirmPhoneChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenericString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).ConfirmPhoneChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.Accounts/ConfirmPhoneChange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).ConfirmPhoneChange(ctx, req.(*GenericString))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_SignOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NilParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).SignOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.Accounts/SignOut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).SignOut(ctx, req.(*NilParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_DeleteAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NilParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).DeleteAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.Accounts/DeleteAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).DeleteAccount(ctx, req.(*NilParam))
	}
	return interceptor(ctx, in, info, handler)
}

var _Accounts_serviceDesc = grpc.ServiceDesc{
	ServiceName: "accounts.Accounts",
	HandlerType: (*AccountsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignUp",
			Handler:    _Accounts_SignUp_Handler,
		},
		{
			MethodName: "CheckAvailability",
			Handler:    _Accounts_CheckAvailability_Handler,
		},
		{
			MethodName: "CreateAccount",
			Handler:    _Accounts_CreateAccount_Handler,
		},
		{
			MethodName: "SignIn",
			Handler:    _Accounts_SignIn_Handler,
		},
		{
			MethodName: "UpdateAccount",
			Handler:    _Accounts_UpdateAccount_Handler,
		},
		{
			MethodName: "UpdateUserName",
			Handler:    _Accounts_UpdateUserName_Handler,
		},
		{
			MethodName: "ChangeEmailAddress",
			Handler:    _Accounts_ChangeEmailAddress_Handler,
		},
		{
			MethodName: "ConfirmEmailChange",
			Handler:    _Accounts_ConfirmEmailChange_Handler,
		},
		{
			MethodName: "ChangePhone",
			Handler:    _Accounts_ChangePhone_Handler,
		},
		{
			MethodName: "ConfirmPhoneChange",
			Handler:    _Accounts_ConfirmPhoneChange_Handler,
		},
		{
			MethodName: "SignOut",
			Handler:    _Accounts_SignOut_Handler,
		},
		{
			MethodName: "DeleteAccount",
			Handler:    _Accounts_DeleteAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accounts.proto",
}

func init() { proto.RegisterFile("accounts.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 576 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x55, 0x5f, 0x6f, 0x12, 0x41,
	0x10, 0xcf, 0x95, 0x82, 0xd7, 0x41, 0xaa, 0xdd, 0x34, 0x16, 0xd1, 0x18, 0x72, 0x0f, 0xda, 0x27,
	0x1e, 0xd0, 0x87, 0x46, 0x8d, 0x86, 0x40, 0x83, 0x8d, 0x09, 0x92, 0x23, 0xf4, 0x7d, 0x39, 0xa6,
	0xb0, 0xe9, 0xb1, 0x87, 0xbb, 0x7b, 0x6d, 0xf8, 0x00, 0x7e, 0x18, 0xe3, 0xab, 0x1f, 0xd0, 0xbb,
	0xdb, 0xfb, 0x0b, 0x08, 0xc6, 0xbe, 0xed, 0xcc, 0xec, 0xfc, 0xe6, 0x37, 0xf3, 0x9b, 0xbd, 0x83,
	0x63, 0xea, 0x38, 0x9e, 0xcf, 0x95, 0x6c, 0x2d, 0x85, 0xa7, 0x3c, 0x62, 0x26, 0xb6, 0x05, 0x60,
	0x0e, 0x98, 0x3b, 0xa4, 0x82, 0x2e, 0xac, 0x77, 0x70, 0xda, 0xb9, 0xa3, 0xcc, 0xa5, 0x13, 0xe6,
	0x32, 0xb5, 0xb2, 0x51, 0x2e, 0x3d, 0x2e, 0x91, 0xbc, 0x84, 0xa3, 0xd8, 0xef, 0x62, 0xdd, 0x68,
	0x1a, 0xe7, 0xa6, 0x9d, 0x39, 0xac, 0x37, 0x50, 0xeb, 0x23, 0x47, 0xc1, 0x9c, 0x91, 0x12, 0x8c,
	0xcf, 0xc8, 0x33, 0xa8, 0xe8, 0x53, 0x74, 0xf7, 0xc8, 0x8e, 0x2d, 0x6b, 0x0c, 0xb5, 0x11, 0x9b,
	0xf1, 0xf1, 0xd2, 0xc6, 0xef, 0x3e, 0x4a, 0x45, 0x2c, 0x78, 0x7c, 0xb9, 0x08, 0x60, 0x3a, 0xd3,
	0xa9, 0x40, 0x29, 0xe3, 0xeb, 0x05, 0x1f, 0x69, 0x42, 0x75, 0x38, 0xf7, 0x38, 0x0e, 0xfc, 0xc5,
	0x04, 0x45, 0xfd, 0x20, 0xba, 0x92, 0x77, 0x59, 0x5f, 0xe1, 0x49, 0x5c, 0x3f, 0x25, 0x1c, 0x31,
	0xa0, 0xca, 0xd7, 0x90, 0x65, 0x3b, 0xb6, 0x42, 0xb0, 0x1e, 0x4a, 0x47, 0xb0, 0xa5, 0x62, 0x1e,
	0x4f, 0xc0, 0x72, 0x2e, 0xeb, 0x87, 0x01, 0xe6, 0x08, 0x95, 0x0a, 0xf8, 0x4a, 0xf2, 0x31, 0x3b,
	0x07, 0x40, 0xa5, 0xf3, 0x6a, 0xbb, 0xd9, 0x4a, 0x07, 0x99, 0x44, 0xd2, 0xc3, 0x25, 0x57, 0x62,
	0x65, 0xa7, 0x19, 0x8d, 0x0f, 0x41, 0xbb, 0xf9, 0x10, 0x79, 0x0a, 0xa5, 0x5b, 0x5c, 0xc5, 0x5d,
	0x86, 0x47, 0x72, 0x0a, 0xe5, 0x3b, 0xea, 0xfa, 0x18, 0x33, 0xd1, 0xc6, 0xfb, 0x83, 0x0b, 0xc3,
	0xfa, 0x65, 0xc0, 0xc9, 0x00, 0xef, 0x3b, 0xba, 0x5a, 0x0f, 0x55, 0x30, 0x12, 0x49, 0x5a, 0x40,
	0xae, 0x83, 0x46, 0x6f, 0x98, 0x43, 0x43, 0xb6, 0x85, 0x29, 0x6f, 0x89, 0x90, 0x06, 0x98, 0x63,
	0x89, 0x82, 0xd3, 0x45, 0x52, 0x22, 0xb5, 0xc3, 0xd8, 0x90, 0x4a, 0x79, 0xef, 0x89, 0x69, 0xbd,
	0xa4, 0x63, 0x89, 0x1d, 0xd4, 0xc9, 0x1a, 0x3f, 0x0c, 0x62, 0xd5, 0x36, 0xd9, 0x6c, 0x3c, 0x6b,
	0xd5, 0xfa, 0x69, 0x68, 0x69, 0xaf, 0x78, 0x22, 0x6d, 0xbe, 0xb2, 0xb1, 0x56, 0x79, 0x5d, 0xf6,
	0x83, 0xfd, 0xb2, 0x97, 0x36, 0x64, 0x2f, 0xf0, 0x3f, 0x5c, 0xe3, 0x1f, 0xc4, 0xae, 0xa9, 0xcb,
	0xa6, 0xc1, 0x12, 0xd7, 0xcb, 0xd1, 0x06, 0xa4, 0xb6, 0xf5, 0x1a, 0x0a, 0x33, 0xf8, 0x1b, 0xcb,
	0xf6, 0xef, 0x0a, 0x98, 0xf1, 0xf8, 0xc3, 0x4d, 0xa8, 0xe8, 0xd5, 0x25, 0x67, 0xb9, 0x41, 0xe4,
	0x97, 0xb9, 0xf1, 0x3c, 0x0b, 0xac, 0xaf, 0x63, 0x1f, 0x4e, 0xba, 0x73, 0x74, 0x6e, 0xf3, 0x8f,
	0x8b, 0xe4, 0x26, 0x9a, 0xd4, 0x6c, 0xbc, 0xca, 0x7c, 0x5b, 0x1f, 0x62, 0x1f, 0x6a, 0x5d, 0x81,
	0x54, 0x61, 0x4c, 0x8c, 0xbc, 0xc8, 0x12, 0x36, 0xb6, 0x65, 0x17, 0xa3, 0xb8, 0x9f, 0x2b, 0xbe,
	0xde, 0x4f, 0xaa, 0xe0, 0xae, 0xec, 0x4f, 0x50, 0x1b, 0x2f, 0xa7, 0x39, 0x1a, 0x5b, 0xb6, 0x63,
	0x57, 0xfe, 0x67, 0x38, 0xd6, 0xf9, 0x61, 0xe3, 0x83, 0x50, 0x88, 0x6d, 0xc3, 0xd8, 0x01, 0xf0,
	0x05, 0x48, 0x77, 0x4e, 0xf9, 0x0c, 0x0b, 0x3b, 0x73, 0xb6, 0x91, 0xa0, 0x9f, 0xc1, 0x3e, 0x24,
	0x8f, 0xdf, 0x30, 0xb1, 0x88, 0xa0, 0x34, 0xea, 0x7f, 0x21, 0x75, 0xa0, 0xaa, 0xb3, 0xa3, 0x25,
	0x7d, 0x20, 0x99, 0x08, 0xe3, 0x01, 0x64, 0x2e, 0xe0, 0x51, 0xa8, 0xe6, 0x37, 0xbf, 0xa0, 0x4d,
	0xf2, 0xa1, 0xdf, 0xa3, 0x6d, 0x0f, 0x5d, 0xdc, 0xaa, 0xed, 0x3f, 0xe4, 0x4f, 0x2a, 0xd1, 0x0f,
	0xe6, 0xed, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x46, 0x9b, 0x11, 0xa7, 0x72, 0x06, 0x00, 0x00,
}
